@startuml

autonumber
actor "Utilizador Não Registado" as UNR

activate UNR
UNR -> ":Sistema" : registar organização
activate ":Sistema"
":Sistema" --> UNR : solicita dados organização \n(nome,NIF, endereço, telefone, website, email)\n e sobre o gestor (nome, função, telefone, email)
deactivate ":Sistema"

UNR -> ":Sistema" : introduz os dados solicitados
activate ":Sistema"
":Sistema" --> UNR : apresenta dados e solicita confirmação
deactivate ":Sistema"

UNR -> ":Sistema" : confirma
activate ":Sistema"
":Sistema" --> UNR : operação bem sucedida
deactivate ":Sistema"

deactivate UNR

@enduml